apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zplooud4r-java-springboot
  janus-idp.io/tekton: zplooud4r-java-springboot
  backstage.io/kubernetes-id: zplooud4r-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zplooud4r-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
